### ISSUE TITLE
Error when running with mujoco 3.0.0

### ISSUE THREAD

**Issue by traversaro** [conda-forge/mujoco-python-viewer-feedstock#2]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Running the sample https://github.com/rohanpsingh/mujoco-python-viewer/blob/edfc2d3dac2d8827feaf0cfd921bafbc88da3c3d/examples/sample.py with mujoco 3.0.0 fails with:
~~~
(mujoco-python-viewer) traversaro@IITICUBLAP257:~/mujoco-python-viewer/examples$ python sample.py
Traceback (most recent call last):
  File "/home/traversaro/mujoco-python-viewer/examples/sample.py", line 40, in <module>
    viewer.render()
  File "/home/traversaro/miniforge3/envs/mujoco-python-viewer/lib/python3.12/site-packages/mujoco_viewer/mujoco_viewer.py", line 458, in render
    update()
  File "/home/traversaro/miniforge3/envs/mujoco-python-viewer/lib/python3.12/site-packages/mujoco_viewer/mujoco_viewer.py", line 385, in update
    self._create_overlay()
  File "/home/traversaro/miniforge3/envs/mujoco-python-viewer/lib/python3.12/site-packages/mujoco_viewer/mujoco_viewer.py", line 322, in _create_overlay
    self.data.solver_iter + 1))
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'mujoco._structs.MjData' object has no attribute 'solver_iter'. Did you mean: 'solver_niter'?
~~~~

### Installed packages

```shell
(mujoco-python-viewer) traversaro@IITICUBLAP257:~/mujoco-python-viewer/examples$ conda list
# packages in environment at /home/traversaro/miniforge3/envs/mujoco-python-viewer:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
absl-py                   2.0.0              pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
ca-certificates           2023.7.22            hbcca054_0    conda-forge
etils                     1.5.1              pyhd8ed1ab_0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
fsspec                    2023.10.0          pyhca7485f_0    conda-forge
glfw                      3.3.8                hd590300_2    conda-forge
imageio                   2.31.5             pyh8c1a49c_0    conda-forge
importlib_resources       6.1.1              pyhd8ed1ab_0    conda-forge
lcms2                     2.15                 hb7c19ff_3    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20230802.1      cxx17_h59595ed_0    conda-forge
libblas                   3.9.0           19_linux64_openblas    conda-forge
libcblas                  3.9.0           19_linux64_openblas    conda-forge
libccd-double             2.1                  h59595ed_3    conda-forge
libdeflate                1.19                 hd590300_0    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_2    conda-forge
libgfortran-ng            13.2.0               h69a702a_2    conda-forge
libgfortran5              13.2.0               ha4646dd_2    conda-forge
libgomp                   13.2.0               h807b86a_2    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
liblapack                 3.9.0           19_linux64_openblas    conda-forge
libmujoco                 3.0.0                hcd4a4b4_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.24          pthreads_h413a1c8_0    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libsqlite                 3.44.0               h2797004_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_2    conda-forge
libtiff                   4.6.0                ha9c0a0a_2    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.3.2                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
lodepng                   20220109             h924138e_0    conda-forge
mujoco-python             3.0.0           py312h7c0956b_0    conda-forge
mujoco-python-viewer      0.1.3              pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  h59595ed_2    conda-forge
numpy                     1.26.0          py312heda63a1_0    conda-forge
openjpeg                  2.5.0                h488ebb8_3    conda-forge
openssl                   3.1.4                hd590300_0    conda-forge
pillow                    10.1.0          py312hf3581a9_0    conda-forge
pip                       23.3.1             pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pyglfw                    2.6.2           py312h7900ff3_1    conda-forge
pyopengl                  3.1.6              pyhd8ed1ab_1    conda-forge
python                    3.12.0          hab00c5b_0_cpython    conda-forge
python_abi                3.12                    4_cp312    conda-forge
pyyaml                    6.0.1           py312h98912ed_1    conda-forge
qhull                     2020.2               h4bd325d_2    conda-forge
readline                  8.2                  h8228510_1    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
tinyxml2                  9.0.0                h9c3ff4c_2    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
typing_extensions         4.8.0              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
wheel                     0.41.3             pyhd8ed1ab_0    conda-forge
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libx11               1.8.7                h8ee46fc_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxcursor           1.2.0                h0b41bf4_1    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-libxinerama          1.1.5                h27087fc_0    conda-forge
xorg-libxrandr            1.5.2                h7f98852_1    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-randrproto           1.5.0             h7f98852_1001    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
```

### Environment info

```shell
(mujoco-python-viewer) traversaro@IITICUBLAP257:~/mujoco-python-viewer/examples$ conda info

     active environment : mujoco-python-viewer
    active env location : /home/traversaro/miniforge3/envs/mujoco-python-viewer
            shell level : 1
       user config file : /home/traversaro/.condarc
 populated config files : /home/traversaro/miniforge3/.condarc
                          /home/traversaro/.condarc
          conda version : 23.3.1
    conda-build version : 3.25.0
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.2=0
                          __glibc=2.35=0
                          __linux=5.15.123.1=0
                          __unix=0=0
       base environment : /home/traversaro/miniforge3  (writable)
      conda av data dir : /home/traversaro/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/robostack-staging/linux-64
                          https://conda.anaconda.org/robostack-staging/noarch
          package cache : /home/traversaro/miniforge3/pkgs
                          /home/traversaro/.conda/pkgs
       envs directories : /home/traversaro/miniforge3/envs
                          /home/traversaro/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.1 requests/2.31.0 CPython/3.10.12 Linux/5.15.123.1-microsoft-standard-WSL2 ubuntu/22.04.3 glibc/2.35 solver/libmamba conda-libmamba-solver/23.3.0 libmambapy/1.4.2
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by traversaro** [comment]
A PR fixing this is proposed upstream in https://github.com/rohanpsingh/mujoco-python-viewer/pull/40 . Probably we can either add this as a patch in the feedstock, or wait for a new `mujoco-python-viewer` release.

Hello @rohanpsingh, do you plan to review/merge anytime soon the PR https://github.com/rohanpsingh/mujoco-python-viewer/pull/40 ? If not, no problem, we can handle this in the recipe by adding a local patch. Thanks in advance!

**Comment by rohanpsingh** [comment]
Hi @traversaro 
I think that PR breaks compatibility with older versions of mujoco. If you can wait until early next week, I can make the fix and merge!
Best,
Rohan

**Comment by traversaro** [comment]
> Hi @traversaro 
> I think that PR breaks compatibility with older versions of mujoco. If you can wait until early next week, I can make the fix and merge!
> Best,
> Rohan

Great, sure we can wait! Thanks a lot again. fyi @CarlottaSartore
